namespace Samples
{
    #region

    using System;
    using System.Globalization;
    using System.IO;
    using System.Threading;

    using Microsoft.VisualStudio.TestTools.UnitTesting;

    using OpenQA.Selenium;
    using OpenQA.Selenium.Interactions;
    using OpenQA.Selenium.Remote;

    #endregion

    [TestClass]
    public class AutoSuggestSample
    {
        #region Fields

        private WpDriver driver;

        #endregion

        #region Public Methods and Operators

        [TestCleanup]
        public void CleanUp()
        {
            this.driver.Quit();
        }

        [TestInitialize]
        public void Initialize()
        {
            var capabillities = new DesiredCapabilities();

            var basePath = Directory.GetCurrentDirectory();
            const string FilePath =
                "..\\..\\..\\..\\TestApp\\TestApp.WindowsPhone\\AppPackages\\TestApp.WindowsPhone_1.0.0.0_AnyCPU_Test\\TestApp.WindowsPhone_1.0.0.0_AnyCPU.appx";
            var autPath = Path.GetFullPath(Path.Combine(basePath, FilePath));

            capabillities.SetCapability("app", autPath);

            this.driver = new WpDriver(new Uri("http://localhost:9999"), capabillities);
        }

        [TestMethod]
        public void TestAutoSuggest()
        {
            this.driver.ExecuteScript("mobile: OnScreenKeyboard.Disable");

            // Go to the second pivot page
            var pivots = this.driver.FindElementsByClassName("Windows.UI.Xaml.Controls.Primitives.PivotHeaderItem");
            pivots[1].Click();
            Thread.Sleep(500);

            // Find AutoSuggestBox element
            var autoSuggestBox = this.driver.FindElementById("MySuggestBox");

            // Find TextBox inside AutoSuggestBox so that we can input some text
            var autoSuggestInput = autoSuggestBox.FindElement(By.ClassName("Windows.UI.Xaml.Controls.TextBox"));

            // Input some text so that suggests list would appear
            autoSuggestInput.SendKeys("A");

            // Wait for animations, don't use Sleep in real tests, use WebDriverWait
            Thread.Sleep(500);

            // Find SuggestionsList, it is generated by framework and has no distinct id, name or class
            // so we have to find it by x:Name and it is not very pretty in C# Selenium bindings as we have to use reflection inside
            var suggestionsList = this.driver.FindByXName("SuggestionsList");

            // suggestionsList contain one ListViewItem per suggestion, each containing two TextBlocks (suggestion valye and some palceholder)
            var suggestions = suggestionsList.FindElements(By.ClassName("Windows.UI.Xaml.Controls.TextBlock"));

            const string Expected = "A2";

            // Lets find suggestion that we want
            foreach (var suggest in suggestions)
            {
                if (!suggest.Text.Equals("A2"))
                {
                    continue;
                }

                /* Unfortunatly when some inputs, including AutoSuggestBox are focused
                 * whole interface is scrolled up, but driver still returns original coordinates
                 * automation: GetClickablePoint is a temporary solution for this problem,
                 * in this case it returns correct coordinates
                */
                var coords = this.driver.ExecuteScript("automation: GetClickablePoint", suggest).ToString().Split(',');

                // Execute script returns string, so now we will have to parse it
                var x = float.Parse(coords[0], CultureInfo.InvariantCulture.NumberFormat);
                var y = float.Parse(coords[1], CultureInfo.InvariantCulture.NumberFormat);
                var ac = new Actions(this.driver);
                ac.MoveByOffset((int)x, (int)y).Click().Perform();

                break;
            }

            // Lets check that we actually selected correct suggestion
            Assert.AreEqual(autoSuggestInput.Text, Expected);
        }

        #endregion
    }
}
